Repository JuulLabs/kable, pull requests merged in 2022-03, with the labels that each got.

#275 Automatically close/release on publication to Sonatype
  .github/workflows/publish.yml
Labels: maintenance

#209 Add Apple Silicon support
  build.gradle.kts
  core/build.gradle.kts
  gradle/libs.versions.toml
Labels: apple

#280 Add ability to create peripheral from identifier
  core/api/core.api
  core/src/androidMain/kotlin/Peripheral.kt
  core/src/appleMain/kotlin/CentralManager.kt
  core/src/appleMain/kotlin/Identifier.kt
  core/src/appleMain/kotlin/Peripheral.kt
  core/src/appleMain/kotlin/Uuid.kt
  core/src/commonMain/kotlin/Identifier.kt
  core/src/commonMain/kotlin/Observers.kt
  core/src/commonMain/kotlin/Peripheral.kt
  core/src/jsMain/kotlin/Identifier.kt
  core/src/jsMain/kotlin/Peripheral.kt
Labels: android, apple

#284 Update Android Gradle configuration and set target API to `30`
  core/build.gradle.kts
  gradle/libs.versions.toml
  log-engine-tuulbox/build.gradle.kts
Labels: android

#287 Add disconnect to Apple peripheral when CBCentralManager turns off
  core/src/appleMain/kotlin/Peripheral.kt
Labels: apple
