Repository JuulLabs/kable, pull requests merged in 2023-01, with the labels that each got.

#396 Add name and address filter in Android
  README.md
  core/api/core.api
  core/src/androidMain/kotlin/Filter.kt
  core/src/androidMain/kotlin/Scanner.kt
Labels: minor

#409 Bump Android compile/target API to 31
  README.md
  core/build.gradle.kts
  core/src/androidMain/AndroidManifest.xml
  gradle/libs.versions.toml
Labels: android, patch

#335 Add `Bluetooth.availability` flow
  core/api/core.api
  core/build.gradle.kts
  core/src/androidMain/kotlin/Bluetooth.kt
  core/src/androidMain/kotlin/broadcastReceiverFlow.kt
  core/src/appleMain/kotlin/Bluetooth.kt
  core/src/commonMain/kotlin/Bluetooth.kt
  core/src/jsMain/kotlin/Bluetooth.kt
  core/src/jsMain/kotlin/external/Bluetooth.kt
  core/src/jsMain/kotlin/external/BluetoothAvailabilityChanged.kt
  gradle/libs.versions.toml
Labels: minor

#411 Fix regression (crash) introduced in #335
  core/src/androidMain/kotlin/Bluetooth.kt
  core/src/androidMain/kotlin/broadcastReceiverFlow.kt
Labels: minor

#408 Rework filter support to have a common API on all platforms
  README.md
  core/api/core.api
  core/src/androidMain/kotlin/Filter.kt
  core/src/androidMain/kotlin/Scanner.kt
  core/src/androidMain/kotlin/ScannerBuilder.kt
  core/src/appleMain/kotlin/AdvertisementData.kt
  core/src/appleMain/kotlin/Filter.kt
  core/src/appleMain/kotlin/Scanner.kt
  core/src/appleMain/kotlin/ScannerBuilder.kt
  core/src/commonMain/kotlin/ByteArray.kt
  core/src/commonMain/kotlin/Filter.kt
  core/src/commonMain/kotlin/Scanner.kt
  core/src/commonMain/kotlin/ScannerBuilder.kt
  core/src/jsMain/kotlin/Bluetooth.kt
  core/src/jsMain/kotlin/Filter.kt
  core/src/jsMain/kotlin/Filters.kt
  core/src/jsMain/kotlin/Options.kt
  core/src/jsMain/kotlin/Scanner.kt
  core/src/jsMain/kotlin/ScannerBuilder.kt
  core/src/jsMain/kotlin/external/Bluetooth.kt
  core/src/jsMain/kotlin/external/BluetoothDataFilterInit.kt
  core/src/jsMain/kotlin/external/BluetoothLEScanFilterInit.kt
  core/src/jsMain/kotlin/external/BluetoothLEScanOptions.kt
  core/src/jsMain/kotlin/external/BluetoothManufacturerDataFilterInit.kt
  core/src/jsMain/kotlin/external/BluetoothServiceDataFilterInit.kt
  core/src/jsMain/kotlin/external/RequestDeviceOptions.kt
  core/src/jsMain/kotlin/jso.kt
Labels: major

#376 Discard response after GATT operation cancellation
  core/src/androidMain/kotlin/BluetoothDevice.kt
  core/src/androidMain/kotlin/Connection.kt
  core/src/androidMain/kotlin/gatt/Callback.kt
  core/src/appleMain/kotlin/CentralManager.kt
  core/src/appleMain/kotlin/Connection.kt
  core/src/appleMain/kotlin/Peripheral.kt
Labels: patch

#415 Mark `Options.Filter`s as deprecated
  core/src/jsMain/kotlin/Options.kt
Labels: minor

#416 Simplify documentation re: Android permissions setup
  README.md
Labels: maintenance

#419 Drop `LEGACY` JavaScript compiler support
  gradle.properties
Labels: major

#418 Escalate deprecations
  core/api/core.api
  core/src/androidMain/kotlin/Peripheral.kt
  core/src/androidMain/kotlin/ScannerBuilder.kt
  core/src/androidMain/kotlin/WriteNotificationDescriptor.kt
  core/src/appleMain/kotlin/ScannerBuilder.kt
  core/src/commonMain/kotlin/Exceptions.kt
  core/src/commonMain/kotlin/Scanner.kt
  core/src/jsMain/kotlin/Options.kt
  core/src/jsMain/kotlin/ScannerBuilder.kt
Labels: major

#421 Add `Bluetooth.BaseUuid` utility for short UUIDs
  core/api/core.api
  core/src/commonMain/kotlin/Bluetooth.kt
  core/src/commonTest/kotlin/BluetoothTests.kt
Labels: minor
