Repository JuulLabs/kable, pull requests merged in 2023-04, with the labels that each got.

#456 Replace deprecated `inline` class modifier with `value`
  core/src/androidMain/kotlin/gatt/Response.kt
Labels: android, patch

#459 Suppress native dependency warnings to quiet AtomicFU warnings
  gradle.properties
Labels: maintenance

#463 Add `address` property to `AndroidPeripheral`
  core/api/core.api
  core/src/androidMain/kotlin/AndroidPeripheral.kt
  core/src/androidMain/kotlin/Peripheral.kt
Labels: minor

#455 Bump Android compile SDK to 33
  core/src/androidMain/kotlin/gatt/Callback.kt
  gradle/libs.versions.toml
Labels: patch

#453 Fix BLE I/O cancellation handling
  core/src/androidMain/kotlin/BluetoothDevice.kt
  core/src/androidMain/kotlin/Connection.kt
  core/src/androidMain/kotlin/Peripheral.kt
  core/src/appleMain/kotlin/CentralManager.kt
  core/src/appleMain/kotlin/Connection.kt
  core/src/appleMain/kotlin/Peripheral.kt
Labels: android, apple, patch

#467 Bluetooth availability - monitor location service changes
  core/src/androidMain/kotlin/Bluetooth.kt
Labels: patch
