Repository JuulLabs/kable, pull requests merged in 2023-07, with the labels that each got.

#520 Fix regression w/ pulling in AtomicFU dependency
  core/build.gradle.kts
  gradle/libs.versions.toml
Labels: patch

#518 Add identifier property to Advertisement object
  core/api/core.api
  core/src/androidMain/kotlin/ScanResultAndroidAdvertisement.kt
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
  core/src/appleMain/kotlin/CoreBluetoothAdvertisement.kt
  core/src/commonMain/kotlin/Advertisement.kt
  core/src/jsMain/kotlin/BluetoothAdvertisingEventWebBluetoothAdvertisement.kt
  core/src/jsMain/kotlin/WebBluetoothAdvertisement.kt
Labels: minor

#512 Move `CBPeripheralCoreBluetoothPeripheral` to its own file
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  core/src/appleMain/kotlin/Peripheral.kt
Labels: apple, maintenance

#530 Only sign local Maven publication on merges to `main`
  .github/workflows/ci.yml
  .github/workflows/signing.yml
Labels: maintenance

#528 Fix typo in Android permission documentation
  README.md
Labels: maintenance

#531 Use `latest` version of GitHub virtual environments
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/publish.yml
  .github/workflows/signing.yml
Labels: maintenance

#527 Update README.md with explicit note about peripheral scope
  README.md
Labels: maintenance

#536 README.md: fix spelling error
  README.md
Labels: maintenance

#537 Remove `flowOn(Main.immediate)` from `advertisements`
  core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
Labels: patch

#542 Use new `androidTarget` Gradle DSL
  log-engine-tuulbox/build.gradle.kts
Labels: maintenance
