Repository JuulLabs/kable, pull requests merged in 2023-11, with the labels that each got.

#582 Android 14 (compile SDK 34) and BroadcastReceiver changes
  core/build.gradle.kts
  core/src/androidMain/kotlin/Bluetooth.kt
  core/src/androidMain/kotlin/broadcastReceiverFlow.kt
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
  gradle/libs.versions.toml
Labels: android, patch

#598 Fix `IOException` to not drop `cause`
  exceptions/src/appleMain/kotlin/Exceptions.kt
  exceptions/src/jsMain/kotlin/Exceptions.kt
Labels: patch

#599 Use default hierarchy template
  core/build.gradle.kts
  exceptions/build.gradle.kts
  log-engine-tuulbox/build.gradle.kts
Labels: maintenance
