Repository JuulLabs/kable, pull requests merged in 2024-12, with the labels that each got.

#801 Change `InternalException` to `InternalError`
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/Connection.kt
  kable-core/src/androidMain/kotlin/bluetooth/CheckBluetoothIsOn.kt
  kable-core/src/androidMain/kotlin/scan/ScanError.kt
  kable-core/src/appleMain/kotlin/Connection.kt
  kable-core/src/appleMain/kotlin/bluetooth/CheckBluetoothIsOn.kt
  kable-core/src/commonMain/kotlin/InternalError.kt
  kable-core/src/commonMain/kotlin/InternalException.kt
  kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
  kable-core/src/jsMain/kotlin/BluetoothWebBluetoothScanner.kt
  kable-core/src/jsMain/kotlin/Connection.kt
  kable-core/src/jsMain/kotlin/RequestPeripheral.kt
  kable-core/src/jsMain/kotlin/bluetooth/IsSupported.kt
Labels: major

#803 Provide `Peripheral(Identifier)` builder function
  kable-core/api/android/kable-core.api
  kable-core/src/androidMain/kotlin/Peripheral.kt
Labels: android, minor

#808 Improve exception message when attempting to `connect` a cancelled peripheral
  README.md
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  kable-core/src/commonMain/kotlin/SharedRepeatableAction.awaitConnect.kt
  kable-core/src/commonMain/kotlin/SharedRepeatableAction.kt
  kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
Labels: patch

#809 Adds maximumWriteValueLength to Peripheral
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  kable-core/src/commonMain/kotlin/Peripheral.kt
  kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
Labels: minor

#758 Use `Uuid` from Kotlin standard library
  gradle/libs.versions.toml
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/build.gradle.kts
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
  kable-core/src/androidMain/kotlin/Profile.kt
  kable-core/src/androidMain/kotlin/ScanResultAndroidAdvertisement.kt
  kable-core/src/androidMain/kotlin/bluetooth/ClientCharacteristicConfigUuid.kt
  kable-core/src/androidMain/kotlin/logs/LogMessage.kt
  kable-core/src/appleMain/kotlin/AdvertisementData.kt
  kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
  kable-core/src/appleMain/kotlin/CentralManager.kt
  kable-core/src/appleMain/kotlin/CentralManagerCoreBluetoothScanner.kt
  kable-core/src/appleMain/kotlin/Identifier.kt
  kable-core/src/appleMain/kotlin/PlatformAdvertisement.kt
  kable-core/src/appleMain/kotlin/Profile.kt
  kable-core/src/appleMain/kotlin/ScannerBuilder.kt
  kable-core/src/appleMain/kotlin/Uuid.kt
  kable-core/src/commonMain/kotlin/Advertisement.kt
  kable-core/src/commonMain/kotlin/Bluetooth.kt
  kable-core/src/commonMain/kotlin/Descriptor.kt
  kable-core/src/commonMain/kotlin/Filter.kt
  kable-core/src/commonMain/kotlin/FilterPredicate.kt
  kable-core/src/commonMain/kotlin/FilterPredicateBuilder.kt
  kable-core/src/commonMain/kotlin/Peripheral.kt
  kable-core/src/commonMain/kotlin/Profile.kt
  kable-core/src/commonMain/kotlin/logs/LogMessage.kt
  kable-core/src/commonMain/kotlin/logs/Logging.kt
  kable-core/src/commonTest/kotlin/FilterPredicateTests.kt
  kable-core/src/commonTest/kotlin/FiltersTests.kt
  kable-core/src/commonTest/kotlin/LogMessageTests.kt
  kable-core/src/commonTest/kotlin/ObservationTest.kt
  kable-core/src/jsMain/kotlin/BluetoothAdvertisingEventWebBluetoothAdvertisement.kt
  kable-core/src/jsMain/kotlin/BluetoothLEScanOptions.kt
  kable-core/src/jsMain/kotlin/Options.deprecated.kt
  kable-core/src/jsMain/kotlin/Options.kt
  kable-core/src/jsMain/kotlin/OptionsBuilder.kt
  kable-core/src/jsMain/kotlin/PlatformAdvertisement.kt
  kable-core/src/jsMain/kotlin/Profile.kt
  kable-core/src/jsMain/kotlin/Uuid.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Profile.kt
Labels: major

#818 Update plugin kotlinter to v5.0.1
  gradle/libs.versions.toml
Labels: maintenance
