Repository JuulLabs/kable, pull requests merged in 2024-07, with the labels that each got.

#702 Use GitHub Actions for documentation deployment
  .github/workflows/documentation.yml
  .github/workflows/pages.yml
Labels: maintenance

#704 Discover descriptors on connect
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  core/src/appleMain/kotlin/CentralManager.kt
  core/src/appleMain/kotlin/PeripheralDelegate.kt
Labels: apple, patch

#695 Enhanced Scan Filtering
  README.md
  core/api/android/core.api
  core/api/jvm/core.api
  core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
  core/src/androidMain/kotlin/ScannerBuilder.kt
  core/src/appleMain/kotlin/CentralManagerCoreBluetoothScanner.kt
  core/src/appleMain/kotlin/ScannerBuilder.kt
  core/src/commonMain/kotlin/Filter.kt
  core/src/commonMain/kotlin/FilterPredicate.kt
  core/src/commonMain/kotlin/FilterPredicateBuilder.kt
  core/src/commonMain/kotlin/FiltersBuilder.kt
  core/src/commonMain/kotlin/ScannerBuilder.kt
  core/src/commonTest/kotlin/FilterPredicateTests.kt
  core/src/commonTest/kotlin/FiltersTests.kt
  core/src/jsMain/kotlin/Bluetooth.kt
  core/src/jsMain/kotlin/BluetoothLEScanOptions.kt
  core/src/jsMain/kotlin/BluetoothWebBluetoothScanner.kt
  core/src/jsMain/kotlin/FilterSet.kt
  core/src/jsMain/kotlin/Filters.kt
  core/src/jsMain/kotlin/Options.kt
  core/src/jsMain/kotlin/ScannerBuilder.kt
  core/src/jvmMain/kotlin/com/juul/kable/ScannerBuilder.kt
Labels: minor

#706 Fix reading of descriptor value as `NSData`
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  core/src/appleTest/kotlin/NSDataTest.kt
  core/src/commonMain/kotlin/ByteArray.kt
  core/src/commonTest/kotlin/ByteArrayTests.kt
Labels: apple, patch

#720 Fix nullability of `connectGattCompat` function
  kable-core/src/androidMain/kotlin/BluetoothDevice.kt
Labels: patch

#722 Add `Options` builder
  README.md
  kable-core/src/jsMain/kotlin/Bluetooth.kt
  kable-core/src/jsMain/kotlin/Options.kt
  kable-core/src/jsMain/kotlin/OptionsBuilder.kt
Labels: javascript, major

#727 Fix closing parenthesis in `Options` builder example in README
  README.md
Labels: maintenance
