Repository JuulLabs/kable, pull requests merged in 2024-04, with the labels that each got.

#661 Re-align the filter shape to work correctly with the browser API
  core/src/jsMain/kotlin/Bluetooth.kt
  core/src/jsMain/kotlin/FilterSet.kt
  core/src/jsMain/kotlin/Options.kt
  core/src/jsMain/kotlin/external/BluetoothDataFilterInit.kt
  core/src/jsMain/kotlin/external/BluetoothManufacturerDataFilterInit.kt
  core/src/jsMain/kotlin/external/BluetoothServiceDataFilterInit.kt
Labels: javascript, major

#665 Fix crash in peripheral `<init>` when parent job is already complete
  core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
Labels: patch

#668 Watch for connection loss during connect
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
Labels: apple, patch
