Repository JuulLabs/kable, pull requests merged in 2024-06, with the labels that each got.

#684 Provide ability to pre-conflate scanned advertisements
  core/api/android/core.api
  core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
  core/src/androidMain/kotlin/ScannerBuilder.kt
Labels: android, minor

#688 K2 support
  core/api/android/core.api
  core/api/jvm/core.api
  core/src/androidMain/kotlin/AndroidAdvertisement.kt
  core/src/androidMain/kotlin/AndroidScanner.kt
  core/src/androidMain/kotlin/BluetoothLeScannerAndroidScanner.kt
  core/src/androidMain/kotlin/PlatformAdvertisement.kt
  core/src/androidMain/kotlin/PlatformScanner.kt
  core/src/androidMain/kotlin/Profile.kt
  core/src/androidMain/kotlin/ScanResultAndroidAdvertisement.kt
  core/src/androidMain/kotlin/ScannerBuilder.kt
  core/src/androidMain/kotlin/logs/SystemLogEngine.kt
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
  core/src/appleMain/kotlin/CentralManagerCoreBluetoothScanner.kt
  core/src/appleMain/kotlin/CentralManagerDelegate.kt
  core/src/appleMain/kotlin/CoreBluetoothAdvertisement.kt
  core/src/appleMain/kotlin/CoreBluetoothScanner.kt
  core/src/appleMain/kotlin/PeripheralDelegate.kt
  core/src/appleMain/kotlin/PlatformAdvertisement.kt
  core/src/appleMain/kotlin/PlatformScanner.kt
  core/src/appleMain/kotlin/Profile.kt
  core/src/appleMain/kotlin/logs/SystemLogEngine.kt
  core/src/commonMain/kotlin/PlatformAdvertisement.kt
  core/src/commonMain/kotlin/PlatformScanner.kt
  core/src/commonMain/kotlin/Profile.kt
  core/src/commonMain/kotlin/Scanner.kt
  core/src/commonMain/kotlin/logs/SystemLogEngine.kt
  core/src/jsMain/kotlin/BluetoothAdvertisingEventWebBluetoothAdvertisement.kt
  core/src/jsMain/kotlin/BluetoothWebBluetoothScanner.kt
  core/src/jsMain/kotlin/PlatformAdvertisement.kt
  core/src/jsMain/kotlin/PlatformScanner.kt
  core/src/jsMain/kotlin/Profile.kt
  core/src/jsMain/kotlin/WebBluetoothAdvertisement.kt
  core/src/jsMain/kotlin/WebBluetoothScanner.kt
  core/src/jsMain/kotlin/external/BluetoothRemoteGATTCharacteristic.kt
  core/src/jsMain/kotlin/external/BluetoothRemoteGATTDescriptor.kt
  core/src/jsMain/kotlin/external/BluetoothRemoteGATTService.kt
  core/src/jsMain/kotlin/logs/SystemLogEngine.kt
  core/src/jvmMain/kotlin/com/juul/kable/PlatformAdvertisement.kt
  core/src/jvmMain/kotlin/com/juul/kable/PlatformScanner.kt
  core/src/jvmMain/kotlin/com/juul/kable/Profile.kt
  core/src/jvmMain/kotlin/com/juul/kable/logs/SystemLogEngine.kt
Labels: major

#689 Remove `log-engine-tuulbox` module
  log-engine-tuulbox/api/android/log-engine-tuulbox.api
  log-engine-tuulbox/api/jvm/log-engine-tuulbox.api
  log-engine-tuulbox/build.gradle.kts
  log-engine-tuulbox/src/commonMain/kotlin/logs/TuulboxLogEngine.kt
  settings.gradle.kts
Labels: major

#690 Replace Tuulbox logging w/ Khronicle
  core/build.gradle.kts
  core/src/commonTest/kotlin/ObservationTest.kt
  gradle/libs.versions.toml
Labels: patch

#692 Prefix Maven artifacts with `kable-`
  core/gradle.properties
  exceptions/gradle.properties
  log-engine-khronicle/gradle.properties
Labels: maintenance

#694 Update Gradle documentation w/ new Maven coordinate
  README.md
Labels: maintenance

#700 Cast to `NSNumber` for determining if advertisement is connectable
  core/src/appleMain/kotlin/CBPeripheralCoreBluetoothAdvertisement.kt
Labels: apple, patch

#699 Ensure teardown is completed when observation coroutines are canceled
  core/src/commonMain/kotlin/Observers.kt
Labels: patch
