Repository JuulLabs/kable, pull requests merged in 2024-02, with the labels that each got.

#626 Add no-op JVM target
  core/api/android/core.api
  core/api/jvm/core.api
  core/build.gradle.kts
  core/src/androidMain/kotlin/Profile.kt
  core/src/jvmMain/kotlin/com/juul/kable/Bluetooth.kt
  core/src/jvmMain/kotlin/com/juul/kable/Exceptions.kt
  core/src/jvmMain/kotlin/com/juul/kable/Identifier.kt
  core/src/jvmMain/kotlin/com/juul/kable/Observations.kt
  core/src/jvmMain/kotlin/com/juul/kable/Peripheral.kt
  core/src/jvmMain/kotlin/com/juul/kable/PeripheralBuilder.kt
  core/src/jvmMain/kotlin/com/juul/kable/PlatformScanner.kt
  core/src/jvmMain/kotlin/com/juul/kable/Profile.kt
  core/src/jvmMain/kotlin/com/juul/kable/ScannerBuilder.kt
  core/src/jvmMain/kotlin/com/juul/kable/logs/Log.kt
  core/src/jvmMain/kotlin/com/juul/kable/logs/SystemLogEngine.kt
  log-engine-tuulbox/api/android/log-engine-tuulbox.api
  log-engine-tuulbox/api/jvm/log-engine-tuulbox.api
  log-engine-tuulbox/build.gradle.kts
Labels: minor

#635 Defensive copying in Android legacy, deprecated `BluetoothGattCallback` functions
  core/src/androidMain/kotlin/gatt/Callback.kt
Labels: android, patch

#636 Remove workaround for `jvmToolchain` not being honored pre AGP 8.1.0-alpha09
  core/build.gradle.kts
  log-engine-tuulbox/build.gradle.kts
Labels: maintenance
