Repository JuulLabs/kable, pull requests merged in 2024-10, with the labels that each got.

#752 Make `isSupported` always `true` on Apple
  kable-core/src/appleMain/kotlin/bluetooth/IsSupported.kt
  kable-core/src/commonMain/kotlin/Bluetooth.kt
Labels: apple, patch

#772 Deprecate `Bluetooth.availability`
  kable-core/src/androidMain/kotlin/Bluetooth.kt
  kable-core/src/appleMain/kotlin/Bluetooth.kt
  kable-core/src/commonMain/kotlin/Bluetooth.kt
  kable-core/src/jsMain/kotlin/BluetoothAvailability.kt
Labels: patch

#769 Drop `kable-exceptions` module and remove unused exceptions
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/build.gradle.kts
  kable-core/src/commonMain/kotlin/Exceptions.deprecated.kt
  kable-core/src/commonMain/kotlin/Exceptions.kt
  kable-core/src/commonMain/kotlin/InternalException.kt
  kable-core/src/commonMain/kotlin/NotConnectedException.kt
  kable-core/src/commonMain/kotlin/UnmetRequirementException.kt
  kable-exceptions/api/kable-exceptions.api
  kable-exceptions/build.gradle.kts
  kable-exceptions/src/commonMain/kotlin/Exceptions.kt
  kable-exceptions/src/commonMain/kotlin/InternalException.kt
  settings.gradle.kts
Labels: major

#771 Drop `ConnectionRejectedException`
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/BluetoothDevice.kt
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/androidMain/kotlin/bluetooth/CheckMacAddress.kt
  kable-core/src/commonMain/kotlin/GattStatusException.kt
  kable-core/src/commonMain/kotlin/Peripheral.kt
  kable-core/src/commonMain/kotlin/bluetooth/CheckBluetoothIsSupported.kt
Labels: android, major

#775 Fix broken links in README.md
  README.md
Labels: maintenance

#779 Have deprecated `CoroutineScope.peripheral` uphold previous behavior
  kable-core/src/androidMain/kotlin/Peripheral.deprecated.kt
Labels: patch
