Repository JuulLabs/kable, pull requests merged in 2025-07, with the labels that each got.

#958 Remove unused `kotlinx.datetime` dependency
  gradle/libs.versions.toml
  kable-core/build.gradle.kts
  kotlin-js-store/yarn.lock
Labels: maintenance

#901 JVM Support
  .gitignore
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  kable-btleplug-ffi/Cargo.lock
  kable-btleplug-ffi/Cargo.toml
  kable-btleplug-ffi/build.gradle.kts
  kable-btleplug-ffi/src/cancellation_handle.rs
  kable-btleplug-ffi/src/characteristic.rs
  kable-btleplug-ffi/src/descriptor.rs
  kable-btleplug-ffi/src/error.rs
  kable-btleplug-ffi/src/lib.rs
  kable-btleplug-ffi/src/peripheral.rs
  kable-btleplug-ffi/src/peripheral_id.rs
  kable-btleplug-ffi/src/peripheral_properties.rs
  kable-btleplug-ffi/src/scan.rs
  kable-btleplug-ffi/src/service.rs
  kable-btleplug-ffi/src/uuid.rs
  kable-btleplug-ffi/src/write_type.rs
  kable-core/api/jvm/kable-core.api
  kable-core/build.gradle.kts
  kable-core/src/jvmMain/kotlin/com/juul/kable/Bluetooth.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Exceptions.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Identifier.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Observations.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Peripheral.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/PeripheralBuilder.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Profile.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/ScannerBuilder.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/bluetooth/IsSupported.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugAdvertisement.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugCharacteristic.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugDescriptor.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugPeripheral.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugScanner.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/btleplug/BtleplugService.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/logs/SystemLogEngine.kt
  settings.gradle.kts
  uniffi-plugin/build.gradle.kts
  uniffi-plugin/gradle
  uniffi-plugin/settings.gradle.kts
  uniffi-plugin/src/main/kotlin/Constants.kt
  uniffi-plugin/src/main/kotlin/ProjectExtensions.kt
  uniffi-plugin/src/main/kotlin/TaskExtensions.kt
  uniffi-plugin/src/main/kotlin/UniffiArch.kt
  uniffi-plugin/src/main/kotlin/UniffiKotlinExtension.kt
  uniffi-plugin/src/main/kotlin/UniffiKotlinPlugin.kt
  uniffi-plugin/src/main/kotlin/UniffiOs.kt
  uniffi-plugin/src/main/kotlin/UniffiTarget.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoBuildTask.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoCheckTask.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoCleanTask.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoFormatTask.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoLintTasks.kt
  uniffi-plugin/src/main/kotlin/tasks/CargoTestTask.kt
  uniffi-plugin/src/main/kotlin/tasks/CopyDynamicLibraryResourcesTask.kt
  uniffi-plugin/src/main/kotlin/tasks/UniffiBindgenTasks.kt
Labels: major, jvm

#962 JVM Publishing
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  kable-btleplug-ffi/build.gradle.kts
  uniffi-plugin/src/main/kotlin/tasks/CopyDynamicLibraryResourcesTask.kt
  uniffi-plugin/src/main/kotlin/tasks/UniffiBindgenTasks.kt
Labels: maintenance, jvm

#965 Compile kable-core JVM on all platforms
  .github/workflows/ci.yml
Labels: maintenance

#974 Support `jvm` label in release drafts and use emojis for logos
  .github/release-drafter.yml
Labels: skip-changelog, maintenance
