Repository JuulLabs/kable, pull requests merged in 2025-06, with the labels that each got.

#891 Bump JVM toolchain to `17`
  gradle/libs.versions.toml
Labels: android, major

#933 Force update disconnection state
  kable-core/src/jsMain/kotlin/Connection.kt
Labels: javascript, patch

#937 Add ability to create `Peripheral` from `ScanResult`
  kable-core/api/android/kable-core.api
  kable-core/src/androidMain/kotlin/Peripheral.kt
Labels: android, minor
