Repository JuulLabs/kable, pull requests merged in 2025-01, with the labels that each got.

#823 Update "maven central" badge to use `kable-core` artifact
  README.md
Labels: maintenance

#831 Fix error string for `GATT_INVALID_ATTRIBUTE_LENGTH`
  kable-core/src/androidMain/kotlin/gatt/Response.kt
Labels: patch

#841 Create copy of `observations` in `Observers.onConnected`
  kable-core/src/commonMain/kotlin/Observers.kt
Labels: patch

#836 Expose Android GATT status `Int` on `GattStatusException`
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/Connection.kt
  kable-core/src/androidMain/kotlin/external/Constants.kt
  kable-core/src/androidMain/kotlin/gatt/Callback.kt
  kable-core/src/androidMain/kotlin/gatt/Response.kt
  kable-core/src/androidMain/kotlin/logs/LogMessage.kt
  kable-core/src/commonMain/kotlin/GattStatusException.kt
  kable-core/src/commonMain/kotlin/android/GattStatus.kt
Labels: major

#834 Support 32-bit (8 hex characters) `CBUUID`s
  kable-core/src/appleMain/kotlin/Uuid.kt
Labels: apple, patch

#837 Simplify "client characteristic config" UUID definition
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/androidMain/kotlin/bluetooth/ClientCharacteristicConfigUuid.kt
  kable-core/src/androidMain/kotlin/external/Constants.kt
Labels: android, patch

#842 Allow for advertisement manufacturer data length to exceed filter data mask length
  kable-core/src/commonMain/kotlin/Filter.kt
  kable-core/src/commonTest/kotlin/FilterPredicateTests.kt
Labels: patch

#838 Move `GattRequestRejectedException` to common
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/Exceptions.kt
  kable-core/src/commonMain/kotlin/GattRequestRejectedException.kt
Labels: minor

#835 Support Web Bluetooth named UUIDs
  README.md
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/commonMain/kotlin/Profile.kt
  kable-core/src/commonMain/kotlin/Uuid.kt
Labels: minor

#839 Convert discovered services, characteristics, descriptors to interfaces
  gradle/libs.versions.toml
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/build.gradle.kts
  kable-core/src/androidMain/kotlin/BluetoothDevice.kt
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/androidMain/kotlin/Connection.kt
  kable-core/src/androidMain/kotlin/Profile.kt
  kable-core/src/androidMain/kotlin/gatt/Callback.kt
  kable-core/src/androidUnitTest/kotlin/com/juul/kable/ProfileTests.kt
  kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  kable-core/src/appleMain/kotlin/CentralManager.kt
  kable-core/src/appleMain/kotlin/Connection.kt
  kable-core/src/appleMain/kotlin/PeripheralDelegate.kt
  kable-core/src/appleMain/kotlin/Profile.kt
  kable-core/src/commonMain/kotlin/ObservationEvent.kt
  kable-core/src/commonMain/kotlin/Profile.kt
  kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
  kable-core/src/jsMain/kotlin/Connection.kt
  kable-core/src/jsMain/kotlin/Profile.kt
  kable-core/src/jvmMain/kotlin/com/juul/kable/Profile.kt
Labels: major

#846 Provide `Peripheral` `CoroutineScope` via `scope` property
  README.md
  kable-core/api/android/kable-core.api
  kable-core/api/jvm/kable-core.api
  kable-core/src/androidMain/kotlin/BluetoothDeviceAndroidPeripheral.kt
  kable-core/src/androidMain/kotlin/Peripheral.deprecated.kt
  kable-core/src/appleMain/kotlin/CBPeripheralCoreBluetoothPeripheral.kt
  kable-core/src/commonMain/kotlin/BasePeripheral.kt
  kable-core/src/commonMain/kotlin/Peripheral.kt
  kable-core/src/jsMain/kotlin/BluetoothDeviceWebBluetoothPeripheral.kt
Labels: major
